name: Rust

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cargo Semver Update
      id: update
      uses: lemonxah/cargo_semver_update@v1.0.1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Commit file
      uses: swinton/commit@v2.x
      env:
        GH_TOKEN: ${{ github.token }}
      with:
        files: |
          Cargo.toml
        commit-message: Updating Cargo semver version to ${{ steps.update.outputs.new_version }}
    - name: Commit tagger
      uses: tvdias/github-tagger@v0.0.2
      with:
        repo-token: ${{ github.token }}
        tag: ${{ steps.update.outputs.new_version_with_v }}
